$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: python train.py
environment:
  conda_file: conda.yml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
compute: azureml:cpu-cluster
code: .
experiment_name: diabetes_training_exp
